# **pandas**

Biblioteca que oferece estruturas de dados muito utilizadas para manipulação de dados em geral.

## *Instalação e Importação*

In [ ]:
#Instalação da biblioteca
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#Importação da biblioteca com alias
import pandas as pd

## *Séries*

Estrutura unidimensional semelhante as listas, que podem possuir qualquer tipo de dado.

Nas séries, cada elemento possui um rótulo (índice), que por padrão são números inteiros, mas que podem ser alterados.

In [ ]:
#Criando uma série a partir de uma lista
numeros = [1,2,3,4]

serie = pd.Series(numeros)
print(serie)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#Ao imprimir uma série, são retornados os valores a direita e seus respectivos
#índices a esquerda

In [ ]:
#Acesso a elementos por índice
print(serie[1])

2

In [ ]:
#Série com índice personalizado
lista = [1981,2019,2022,2025]
index = ['primeiro', 'bi', 'tri', 'tetra']

serie2 = pd.Series(lista, index)
print(serie2)

primeiro    1981
bi          2019
tri         2022
tetra       2025
dtype: int64

In [ ]:
#Criando uma série a partir de um dicionário
albuns = {
  'IGOR' : 2019,
  'Astroworld' : 2018,
  'Swimming' : 2018
}
print(albuns)
print()

serie3 = pd.Series(albuns)
print(serie3)

{'IGOR': 2019, 'Astroworld': 2018, 'Swimming': 2018}

IGOR          2019
Astroworld    2018
Swimming      2018
dtype: int64

## *DataFrames*

Estrutura bidimensional tabular, que possui linhas e colunas, assim como as matrizes.

Semelhantes a tabelas de bancos de dados e planilhas do Excel, é formada por um conjunto de Séries juntas lado a lado.

In [ ]:
#Criando um DataFrame a partir de um dicionário
#No dicionário, as chaves representam as colunas, enquanto os valores são
#armazenados nas linhas.
vingadores = {
    'Nome' : ['Neymar', 'Cristiano Ronaldo', 'Messi'],
    'Altura' : [1.74, 1.87, 1.70],
    'Idade' : [34, 41, 39]
}
print(vingadores)
print()

df = pd.DataFrame(vingadores)
print(df)

{'Nome': ['Neymar', 'Cristiano Ronaldo', 'Messi'], 'Altura': [1.74, 1.87, 1.7], 'Idade': [34, 41, 39]}

                Nome  Altura  Idade
0             Neymar    1.74     34
1  Cristiano Ronaldo    1.87     41
2              Messi    1.70     39

In [ ]:
#Acessando o DF por uma coluna específica
print(df.Nome)

0               Neymar
1    Cristiano Ronaldo
2                Messi
Name: Nome, dtype: object

In [ ]:
print(df['Nome'])

0               Neymar
1    Cristiano Ronaldo
2                Messi
Name: Nome, dtype: object

In [ ]:
#Criando um DF a partir de uma lista de dicionários
cidades = [
    {'Nome' : 'Cuiabá', 'Estado' : 'Mato Grosso'},
    {'Nome' : 'São Carlos', 'Estado' : 'São Paulo'},
    {'Nome' : 'Rio de Janeiro', 'Estado' : 'Rio de Janeiro'},
    {'Nome' : 'Xique-Xique', 'Estado' : 'Bahia'}
]
print(cidades)
print()

df2 = pd.DataFrame(cidades)
print(df2)

[{'Nome': 'Cuiabá', 'Estado': 'Mato Grosso'}, {'Nome': 'São Carlos', 'Estado': 'São Paulo'}, {'Nome': 'Rio de Janeiro', 'Estado': 'Rio de Janeiro'}, {'Nome': 'Xique-Xique', 'Estado': 'Bahia'}]

             Nome          Estado
0          Cuiabá     Mato Grosso
1      São Carlos       São Paulo
2  Rio de Janeiro  Rio de Janeiro
3     Xique-Xique           Bahia

In [ ]:
print(df2.Nome)

0            Cuiabá
1        São Carlos
2    Rio de Janeiro
3       Xique-Xique
Name: Nome, dtype: object

## *Ler e Salvar*

In [24]:
#Leitura de arquivos csv - arquivo que armazena dados tabulares
url = 'https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv' #link de arquivo csv genérico

df = pd.read_csv(url)
print(df)

          country  year         pop continent  lifeExp   gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1     Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2     Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3     Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4     Afghanistan  1972  13079460.0      Asia   36.088  739.981106
...           ...   ...         ...       ...      ...         ...
1699     Zimbabwe  1987   9216418.0    Africa   62.351  706.157306
1700     Zimbabwe  1992  10704340.0    Africa   60.377  693.420786
1701     Zimbabwe  1997  11404948.0    Africa   46.809  792.449960
1702     Zimbabwe  2002  11926563.0    Africa   39.989  672.038623
1703     Zimbabwe  2007  12311143.0    Africa   43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
#Leitura de arquivos xlsx - planilhas do Excel
pd.read_excel()

In [25]:
#Salvar um DF em formato csv
df3 = pd.DataFrame({
    'Nome' : ['Supra', 'Rx-7', 'GT-R R33'],
    'Marca' : ['Toyota', 'Mazda', 'Nissan']
})
print(df3)

df3.to_csv('carros_jdm.csv', index = False) #salva o DF no formato csv
#df.to_csv('nome_df.csv', index=false or true)

       Nome   Marca
0     Supra  Toyota
1      Rx-7   Mazda
2  GT-R R33  Nissan

In [26]:
#Verificando se o salvamento foi correto
df4 = pd.read_csv('carros_jdm.csv')
print(df4)

       Nome   Marca
0     Supra  Toyota
1      Rx-7   Mazda
2  GT-R R33  Nissan

## *Funções da Biblioteca*

In [31]:
df = pd.DataFrame({
    'Nome' : ['Neymar', 'Cristiano Ronaldo', 'Messi', 'Mbappé', 'Yamal'],
    'Altura' : [1.74, 1.87, 1.70, 1.78, 1.78],
    'Idade' : [34, 41, 39, 27,18],
    'Time' : ['Santos', 'Al Nassr', 'Inter Miami', 'Real Madrid','Barcelona']
})
print(df)

                Nome  Altura  Idade         Time
0             Neymar    1.74     34       Santos
1  Cristiano Ronaldo    1.87     41     Al Nassr
2              Messi    1.70     39  Inter Miami
3             Mbappé    1.78     27  Real Madrid
4              Yamal    1.78     18    Barcelona

### head(n)

Retorna as primeiras **n** linhas do DataFrame.

Por padrão, a função retorna as 5 primeiras linhas do DF.

In [41]:
#Retornando as 2 primeiras linhas
df.head(2)

                Nome  Altura  Idade      Time
0             Neymar    1.74     34    Santos
1  Cristiano Ronaldo    1.87     41  Al Nassr

In [40]:
df.head()

                Nome  Altura  Idade         Time
0             Neymar    1.74     34       Santos
1  Cristiano Ronaldo    1.87     41     Al Nassr
2              Messi    1.70     39  Inter Miami
3             Mbappé    1.78     27  Real Madrid
4              Yamal    1.78     18    Barcelona

### tail(n)

Retorna as n últimas linhas do DF.
Como padrão retorna as 5 últimas.

In [42]:
df.tail(2)

     Nome  Altura  Idade         Time
3  Mbappé    1.78     27  Real Madrid
4   Yamal    1.78     18    Barcelona

In [43]:
df.tail()

                Nome  Altura  Idade         Time
0             Neymar    1.74     34       Santos
1  Cristiano Ronaldo    1.87     41     Al Nassr
2              Messi    1.70     39  Inter Miami
3             Mbappé    1.78     27  Real Madrid
4              Yamal    1.78     18    Barcelona

### shape

Retorna a dimensão do DF, ou seja, a quantidade de linhas e colunas.

In [38]:
df.shape

(5, 4)

### info()

Fornece um resumo do DF, como:


*   Número de linhas e colunas
*   Tipos de dados de cada linha
*   Utilização de memória

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    5 non-null      object
 1   Altura  5 non-null      float64
 2   Idade   5 non-null      int64
 3   Time    5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

### describe()

Retorna estatísticas sobre o DF:


*   **count**: quantidade de valores válidos (excluindo NULL)
*  ** mean** média aritmética dos valores
*   **std:** desvio padrão
*   **min:** valor mínimo
*  ** 25%:** primeiro quartil
*  ** 50%:** mediana
*   **75%:** terceiro quartil
*   **max:** valor máximo

In [45]:
df.describe()

         Altura      Idade
count  5.000000   5.000000
mean   1.774000  31.800000
std    0.063087   9.418068
min    1.700000  18.000000
25%    1.740000  27.000000
50%    1.780000  34.000000
75%    1.780000  39.000000
max    1.870000  41.000000

## *Loc e Iloc*